package com.example.testchartview

import android.os.Bundle
import android.view.View
import androidx.appcompat.app.AppCompatActivity
import com.example.chart.chart_view.ChartView
import com.example.chart.chart_view.data.InputData
import java.util.concurrent.TimeUnit

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        val chart = findViewById<ChartView>(R.id.chart)
        chart.setData(createChartData())
    }

    private fun createChartData(): List<InputData> {
        val dataList: MutableList<InputData> = ArrayList<InputData>()
        dataList.add(InputData(1))
        dataList.add(InputData(2))
        dataList.add(InputData(3))
        dataList.add(InputData(4))
        dataList.add(InputData(5))
        dataList.add(InputData(6))
        dataList.add(InputData(7))
        dataList.add(InputData(20))
        dataList.add(InputData(9))
        dataList.add(InputData(10))
        dataList.add(InputData(11))
        dataList.add(InputData(12))
        dataList.add(InputData(11))
        dataList.add(InputData(10))
        dataList.add(InputData(9))
        dataList.add(InputData(8))
        dataList.add(InputData(7))
        dataList.add(InputData(6))
        dataList.add(InputData(5))
        dataList.add(InputData(4))
        dataList.add(InputData(3))
        dataList.add(InputData(2))
        dataList.add(InputData(1))
        dataList.add(InputData(2))
        dataList.add(InputData(3))
        dataList.add(InputData(4))
        dataList.add(InputData(5))
        dataList.add(InputData(6))
        dataList.add(InputData(7))
        dataList.add(InputData(20))
        dataList.add(InputData(9))
        dataList.add(InputData(10))
        dataList.add(InputData(11))
        dataList.add(InputData(12))
        dataList.add(InputData(11))
        dataList.add(InputData(10))
        dataList.add(InputData(9))
        dataList.add(InputData(8))
        dataList.add(InputData(7))
        dataList.add(InputData(6))
        dataList.add(InputData(5))
        dataList.add(InputData(4))
        dataList.add(InputData(3))
        dataList.add(InputData(2))
        dataList.add(InputData(1))
        dataList.add(InputData(2))
        dataList.add(InputData(3))
        dataList.add(InputData(4))
        dataList.add(InputData(5))
        dataList.add(InputData(6))
        dataList.add(InputData(7))
        dataList.add(InputData(20))
        dataList.add(InputData(9))
        dataList.add(InputData(10))
        dataList.add(InputData(11))
        dataList.add(InputData(12))
        dataList.add(InputData(11))
        dataList.add(InputData(10))
        dataList.add(InputData(9))
        dataList.add(InputData(8))
        dataList.add(InputData(7))
        dataList.add(InputData(6))
        dataList.add(InputData(5))
        dataList.add(InputData(4))
        dataList.add(InputData(3))
        dataList.add(InputData(2))
        dataList.add(InputData(1))
        dataList.add(InputData(2))
        dataList.add(InputData(3))
        dataList.add(InputData(4))
        dataList.add(InputData(5))
        dataList.add(InputData(6))
        dataList.add(InputData(7))
        dataList.add(InputData(20))
        dataList.add(InputData(9))
        dataList.add(InputData(10))
        dataList.add(InputData(11))
        dataList.add(InputData(12))
        dataList.add(InputData(11))
        dataList.add(InputData(10))
        dataList.add(InputData(9))
        dataList.add(InputData(8))
        dataList.add(InputData(7))
        dataList.add(InputData(6))
        dataList.add(InputData(5))
        dataList.add(InputData(4))
        dataList.add(InputData(3))
        dataList.add(InputData(2))
        dataList.add(InputData(1))
        dataList.add(InputData(2))
        dataList.add(InputData(3))
        dataList.add(InputData(4))
        dataList.add(InputData(5))
        dataList.add(InputData(6))
        dataList.add(InputData(7))
        dataList.add(InputData(20))
        dataList.add(InputData(9))
        dataList.add(InputData(10))
        dataList.add(InputData(11))
        dataList.add(InputData(12))
        dataList.add(InputData(11))
        dataList.add(InputData(10))
        dataList.add(InputData(9))
        dataList.add(InputData(8))
        dataList.add(InputData(7))
        dataList.add(InputData(6))
        dataList.add(InputData(5))
        dataList.add(InputData(4))
        dataList.add(InputData(3))
        dataList.add(InputData(2))
        dataList.add(InputData(1))
        dataList.add(InputData(2))
        dataList.add(InputData(3))
        dataList.add(InputData(4))
        dataList.add(InputData(5))
        dataList.add(InputData(6))
        dataList.add(InputData(7))
        dataList.add(InputData(20))
        dataList.add(InputData(9))
        dataList.add(InputData(10))
        dataList.add(InputData(11))
        dataList.add(InputData(12))
        dataList.add(InputData(11))
        dataList.add(InputData(10))
        dataList.add(InputData(9))
        dataList.add(InputData(8))
        dataList.add(InputData(7))
        dataList.add(InputData(6))
        dataList.add(InputData(5))
        dataList.add(InputData(4))
        dataList.add(InputData(3))
        dataList.add(InputData(2))
        dataList.add(InputData(1))
        dataList.add(InputData(2))
        dataList.add(InputData(3))
        dataList.add(InputData(4))
        dataList.add(InputData(5))
        dataList.add(InputData(6))
        dataList.add(InputData(7))
        dataList.add(InputData(20))
        dataList.add(InputData(9))
        dataList.add(InputData(10))
        dataList.add(InputData(11))
        dataList.add(InputData(12))
        dataList.add(InputData(11))
        dataList.add(InputData(10))
        dataList.add(InputData(9))
        dataList.add(InputData(8))
        dataList.add(InputData(7))
        dataList.add(InputData(6))
        dataList.add(InputData(5))
        dataList.add(InputData(4))
        dataList.add(InputData(3))
        dataList.add(InputData(2))
        dataList.add(InputData(1))
        dataList.add(InputData(2))
        dataList.add(InputData(3))
        dataList.add(InputData(4))
        dataList.add(InputData(5))
        dataList.add(InputData(6))
        dataList.add(InputData(7))
        dataList.add(InputData(20))
        dataList.add(InputData(9))
        dataList.add(InputData(10))
        dataList.add(InputData(11))
        dataList.add(InputData(12))
        dataList.add(InputData(11))
        dataList.add(InputData(10))
        dataList.add(InputData(9))
        dataList.add(InputData(8))
        dataList.add(InputData(7))
        dataList.add(InputData(6))
        dataList.add(InputData(5))
        dataList.add(InputData(4))
        dataList.add(InputData(3))
        dataList.add(InputData(2))
        dataList.add(InputData(1))
        dataList.add(InputData(2))
        dataList.add(InputData(3))
        dataList.add(InputData(4))
        dataList.add(InputData(5))
        dataList.add(InputData(6))
        dataList.add(InputData(7))
        dataList.add(InputData(20))
        dataList.add(InputData(9))
        dataList.add(InputData(10))
        dataList.add(InputData(11))
        dataList.add(InputData(12))
        dataList.add(InputData(11))
        dataList.add(InputData(10))
        dataList.add(InputData(9))
        dataList.add(InputData(8))
        dataList.add(InputData(7))
        dataList.add(InputData(6))
        dataList.add(InputData(5))
        dataList.add(InputData(4))
        dataList.add(InputData(3))
        dataList.add(InputData(2))
        var currMillis = System.currentTimeMillis()
        currMillis -= currMillis % TimeUnit.DAYS.toMillis(1)
        for (i in dataList.indices) {
            val position = (dataList.size - 1 - i).toLong()
            val offsetMillis = TimeUnit.DAYS.toMillis(position)
            val millis = currMillis - offsetMillis
            dataList[i].millis = millis
        }
        return dataList
    }

}